// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: proto/pala.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PalaClient is the client API for Pala service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PalaClient interface {
	Send(ctx context.Context, in *InnoPacket, opts ...grpc.CallOption) (*Response, error)
}

type palaClient struct {
	cc grpc.ClientConnInterface
}

func NewPalaClient(cc grpc.ClientConnInterface) PalaClient {
	return &palaClient{cc}
}

func (c *palaClient) Send(ctx context.Context, in *InnoPacket, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Pala/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PalaServer is the server API for Pala service.
// All implementations must embed UnimplementedPalaServer
// for forward compatibility
type PalaServer interface {
	Send(context.Context, *InnoPacket) (*Response, error)
	mustEmbedUnimplementedPalaServer()
}

// UnimplementedPalaServer must be embedded to have forward compatible implementations.
type UnimplementedPalaServer struct {
}

func (UnimplementedPalaServer) Send(context.Context, *InnoPacket) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedPalaServer) mustEmbedUnimplementedPalaServer() {}

// UnsafePalaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PalaServer will
// result in compilation errors.
type UnsafePalaServer interface {
	mustEmbedUnimplementedPalaServer()
}

func RegisterPalaServer(s grpc.ServiceRegistrar, srv PalaServer) {
	s.RegisterService(&Pala_ServiceDesc, srv)
}

func _Pala_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InnoPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PalaServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Pala/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PalaServer).Send(ctx, req.(*InnoPacket))
	}
	return interceptor(ctx, in, info, handler)
}

// Pala_ServiceDesc is the grpc.ServiceDesc for Pala service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pala_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Pala",
	HandlerType: (*PalaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Pala_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pala.proto",
}
